[build]
  command = "npm run build"
  publish = "."

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/.netlify/identity/*"
  to = "/.netlify/identity/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
