backend:
  name: github
  repo: taylors040/wine-website
  branch: main
  auth_type: token

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "wines"
    label: "Wines"
    folder: "content/wines"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Type", name: "type", widget: "string" }
      - { label: "Region", name: "region", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }